### ISSUE TITLE
ModuleNotFoundError: No module named 'evaluate_utils'

### ISSUE THREAD

**Issue by schxnhxlz** [zhangzc21/DynTet#12]
Hey there,

again. Great Project! I sucessfully managed to complete the training on a GCP Ubuntu 20.04 VM Instance. But after the training I try to evaluate and get this error. Any Idea whats happening here?

 <img width="856" alt="Screenshot 2024-04-25 at 06 01 43" src="https://github.com/zhangzc21/DynTet/assets/58291636/8bf87088-8836-4d58-993f-c1fbdb687c35">

File Structure:

<img width="271" alt="Screenshot 2024-04-25 at 06 03 28" src="https://github.com/zhangzc21/DynTet/assets/58291636/29e959cd-9c97-493f-9daa-b4fd430aabf7">

Thanks!

**Comment by schxnhxlz** [comment]
`(dyntet) schoenholz@dyntet:~/DynTet$ python evaluate_utils/evaluate.py --train_dir out/robertcar
Traceback (most recent call last):
  File "/home/schoenholz/DynTet/evaluate_utils/evaluate.py", line 15, in <module>
    from evaluate_utils.metrics import PSNRMeter, LPIPSMeter, LMDMeter, FIDMeter, ArcfaceMeter
ModuleNotFoundError: No module named 'evaluate_utils'`

**Comment by schxnhxlz** [comment]
I added `import sys
sys.path.insert(0, '/home/user/DynTet')` at the very beginning of `evaluate.py` and it worked. 

Closed

**Comment by hereTac** [comment]
> I added `import sys sys.path.insert(0, '/home/user/DynTet')` at the very beginning of `evaluate.py` and it worked.
> 
> Closed

Yep. Or just change the path. 
`from evaluate_utils.metrics import PSNRMeter, LPIPSMeter, LMDMeter, FIDMeter, ArcfaceMeter`
`from metrics import PSNRMeter, LPIPSMeter, LMDMeter, FIDMeter, ArcfaceMeter`
