### ISSUE TITLE
Question to the Obama_sing_sadtalker.npy

### ISSUE THREAD

**Issue by schxnhxlz** [zhangzc21/DynTet#13]
Hello hello,

its me again. What does this mean? `--drive_3dmm data/test_audio/obama_sing_sadtalker.npy`
How can I create this npy for my own video? Is it necessary? Or whats the best approach to insert an audio file and get the lip sync video back?

thanks!

**Comment by hereTac** [comment]
Just use SadTalk. https://github.com/OpenTalker/SadTalker
`.npy` file is generated from your target audio wav or mp3.
You can use [colab](https://colab.research.google.com/github/Winfredy/SadTalker/blob/main/quick_demo.ipynb) as the simplest way to generate the `.npy` file.

**Comment by schxnhxlz** [comment]
Worked thank you!
