### ISSUE TITLE
 The system cannot find the specified path

### ISSUE THREAD

**Issue by brazilgithub** [zhangzc21/DynTet#2]
I tried to run the script to process the video and the system is reporting that the video path cannot be found. I put the video obama.mp4 in the data\video folder. What should I do?

![error](https://github.com/zhangzc21/DynTet/assets/61645540/12254225-1412-4131-a233-b110d9f9d5ca)

(DynTet) D:\DynTet>python data_utils/process.py --path "data/video/obama.mp4" --save_dir "data/video/obama" --task -1
[INFO] ===== extract audio from data/video/obama.mp4 to data/video/obama\aud.wav =====
O sistema não pode encontrar o caminho especificado.
[INFO] ===== extracted audio =====
[INFO] ===== extract images from data/video/obama.mp4 to data/video/obama\ori_imgs =====
/usr/bin/ffmpeg -y -i data/video/obama.mp4 -vf "scale=trunc(iw/16)*16:trunc(ih/16)*16" -c:a copy -c:v h264 -crf 20 C:\Users\Bruno\AppData\Local\Temp\tmpho67t3d5.mp4
O sistema não pode encontrar o caminho especificado.
Traceback (most recent call last):
  File "D:\DynTet\data_utils\process.py", line 525, in <module>
    extract_images(opt.path, ori_imgs_dir)
  File "D:\DynTet\data_utils\process.py", line 36, in extract_images
    assert return_code == 0
AssertionError

**Comment by zhangzc21** [comment]
I have only tested the code on a Linux service. It seems to be an error caused by FFMPEG, you can try 
1. changing this ffmpeg path  to the ffmpeg path on your system.
https://github.com/zhangzc21/DynTet/blob/b6c1306b8231a932334b43e08aa3c0c405f2bb3c/data_utils/process.py#L10

2. Using Linux system..

**Comment by brazilgithub** [comment]
Thanks for quick answer. I changed the ffmpeg path in the process,py file, but the error still persists. I tried using Google Colab and it still doesn't work.
![sssssssssss](https://github.com/zhangzc21/DynTet/assets/61645540/76722f97-c21a-45cb-a2de-3ef536fc536a)

**Comment by zhangzc21** [comment]
I just tested some of the data processing code in colab,  maybe you can refer to it.
https://colab.research.google.com/drive/1abTJPEeGErSwKVYDnHuJ4pzGCBgj2GUT?usp=sharing
