### ISSUE TITLE
How do I generate a 3dmm?

### ISSUE THREAD

**Issue by einsqing** [zhangzc21/DynTet#6]
How do I generate a 3dmm? face_recon3dmm.npy?or do I use this method? https://github.com/OpenTalker/SadTalker/blob/cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8/src/utils/preprocess.py#L46

**Comment by zhangzc21** [comment]
You can use SadTalker to generate 3DMM coefficients in the mat file

https://github.com/zhangzc21/DynTet/blob/025664e459aa5041fcde2c666a3b36830c856c7d/infer.py#L51
