### ISSUE TITLE
How to post the generated header video?

### ISSUE THREAD

**Issue by einsqing** [zhangzc21/DynTet#8]
How to post the generated header video?

**Comment by einsqing** [comment]
@zhangzc21 This post is different from the ernerf. Can't the deduced video be posted back to the original video?

**Comment by zhangzc21** [comment]
Hi, I cannot get the meaning of "post the generated header video". Can you explain it in detail?

**Comment by einsqing** [comment]
> Hi, I cannot get the meaning of "post the generated header video". Can you explain it in detail?

生成的头部视频，如何贴回原视频？

**Comment by zhangzc21** [comment]
Sorry for the late response. Check here https://github.com/zhangzc21/DynTet/issues/10#issuecomment-2071341837
